// components/Layout.js

import { ReactNode } from 'react';
import Navbar from './Navbar';
import Sidebar from './Sidebar';
import Head from 'next/head';


type LayoutProps = {
    children: ReactNode
    pageTitle?:string
}

const DashboardLayout = ({ children ,pageTitle = 'Home'}:LayoutProps) => {
  return (
    <>
       <Head>
        <title>{pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div className="flex h-screen">

      <Sidebar />
      <div className="flex-1 flex flex-col overflow-hidden">
        <Navbar />
        <main className="flex-1 p-16 overflow-x-hidden overflow-y-auto bg-gray-200">
          {children}
        </main>
      </div>
    </div>
    </>
  );
};

export default DashboardLayout;
